### ISSUE TITLE
iframes stripped

### ISSUE THREAD

**Issue by hsuh** [frozeman/MediaEmbed#9]
Hi I'm using the latest ckeditor 4.4.5.
When I use MediaEmbed the iframes are stripped leaving a border with the word iframe in red. I've tried several things to fix this. 

I tried various settings
config.allowedContent = true
config.extraAllowedContent = 'p(_)[_]{_};div[id];iframe[_];html[_];script[_]';
config.extraPlugins = 'mediaembed';

I wonder if you could help? Thanks.

**Comment by frozeman** [comment]
i didn't looked into this project since over a year and have no setup to test on my computer.
seems like a creditor problem to me. something wrong with the plugin setup maybe?

**Comment by hsuh** [comment]
Hi thanks for the reply. It's just when I click on edit again on the form or when I click on "source" button and back to normal view that iframe became blank. 
Similar to this stackoverflow problem - http://stackoverflow.com/questions/15753956/ckeditor-strips-inline-attributes
It might as well be ckeditor issue as you said.

**Comment by hsuh** [comment]
ah.. I found the culprit. I had to do config.removePlugins = 'iframe'; so that the default red square is not shown.
http://ckeditor.com/forums/CKEditor/Editing-iframe-preview

**Comment by frozeman** [comment]
thanks
